### ISSUE TITLE
Make `bionetgen.modelapi.structs.Action.args` a dictionary

### ISSUE THREAD

**Issue by jonrkarr** [RuleWorld/PyBioNetGen#15]
Unless arguments can be repeated, it would be helpful for this to be a dictionary rather than a list of key-value tuples.

**Comment by ASinanSaglam** [comment]
This and #16 will be resolved shortly, will update very soon.

**Comment by ASinanSaglam** [comment]
Fixed with 0.4.6 release

**Comment by jonrkarr** [comment]
FYI, this is still a list of tuples in 0.4.6. This representation is fine. Users can easily be convert it to a dictionary if needed.

**Comment by ASinanSaglam** [comment]
I agree with the initial suggestion. I'll make 0.4.7 release today and it'll be fixed with it.

**Comment by ASinanSaglam** [comment]
Should be fixed with 0.4.7
