### ISSUE TITLE
BUG: `bionetgen.bngmodel` fails when action block is empty or undefined

### ISSUE THREAD

**Issue by jonrkarr** [RuleWorld/PyBioNetGen#17]
However, `bionetgen.bngmodel` succeeds when there is an action block with actions that are all commented out

**Comment by jonrkarr** [comment]
This problem was introduced between 0.3.1 and 0.3.9.

**Comment by jonrkarr** [comment]
This appears to be fixed with 0.4.3

**Comment by ASinanSaglam** [comment]
Forgot to link to the issue in the commit and close it, sorry! 

We now have a test for this so this shouldn't happen again. We'll soon start looking into the remaining parsing issues
