### ISSUE TITLE
Parse all actions (e.g., including `setModelName`) 

### ISSUE THREAD

**Issue by jonrkarr** [RuleWorld/PyBioNetGen#18]
The new version appears to parse some, but not all actions

**Comment by ASinanSaglam** [comment]
This should also be fixed with the next release, along with #24

**Comment by jonrkarr** [comment]
This appears to be fixed in 0.4.6

**Comment by ASinanSaglam** [comment]
This actually reminded me another issue, `setModelName` and several other actions needs to be used _before_ the model. This will be fixed in the upcoming version.
