### ISSUE TITLE
Provide option to read the raw model definition rather than the resolved description

### ISSUE THREAD

**Issue by jonrkarr** [RuleWorld/PyBioNetGen#3]
`bionetgen.bngmodel` nicely parses models. It would helpful to have an option to read the original model description (with mathematical expressions) rather than a resolved version of the model description (with mathematical expressions replaced with their results).

For example
```
begin parameters
 Vcell 1000 # Typical eukaryotic cell volume ~ 1000 um^3
 Vec   1000*Vcell # Volume of extracellular space around each cell (1/cell density)
end parameters

begin compartments
  EC 3 Vec
end compartments
```

is parsed to 
```
begin parameters
 Vcell 1000
 Vec   1000*Vcell
end parameters

begin compartments
  EC 3 1000000
end compartments
```

The original link between the size of `EC` and the parameter `Vec` has been resolved away.

**Comment by ASinanSaglam** [comment]
This will take a bit but I will add this in (I need to adjust how XML outputting works which is why it'll take a bit). The unresolved expressions will be added as a separate attribute and that attribute will be the default one to output during model string generation.

**Comment by jonrkarr** [comment]
Having both the resolved and unresolved values would be great.

**Comment by ASinanSaglam** [comment]
Forgot to close this, this is fully functional now. Expressions will be outputted by default, if they exist, and values are also stored with the parameters.
