### ISSUE TITLE
Adding molecule types

### ISSUE THREAD

**Issue by Hamzaahmed0** [RuleWorld/PyBioNetGen#54]
Is it possible to add new molecule types and then add them to new reaction rules using just PyBioNetGen. I would like to be able to create new molecules using a script rather than going into the bngl file. The follow-up question would be if after adding these new molecules, could reaction rules be generated using PyBioNetGen as well?

**Comment by jrfaeder** [comment]
We are currently working on testing and expanding functionality for using PyBioNetGen to create and modify models. We will provide updates and examples in the near future.
