### ISSUE TITLE
Strings generated from Parameter objects do not print the correct value

### ISSUE THREAD

**Issue by aadibiasi** [RuleWorld/PyBioNetGen#56]
To construct a `Parameter` object, a `name` and `value` are required and there can be an optional `expr`. Whether or not the parameter you wish to add is a value or expression, a `value` must be provided. The intention of the `Parameter` constructor is to pick between the `value` and `expr` variables when generating the string that incorporates BNG syntax. To test whether or not `expr` needs to be chosen, it tries to cast it to a `float`. If it can be cast to a `float`, then there is no expression, and the generated string will use the `value` variable. If `expr` cannot be cast to a `float` then the generated string will use the `expr` variable. The intention is that if there is an expression, then `expr` will contain operators or the names of other parameters, and thus cannot be cast to a `float`. The problem is that if only a `value` is provided, `expr` is set to `None` which cannot be cast to a `float`. The resulting string will contain the parameter name as intended followed by `None` because it could not be cast to a `float`. It is important to note that `value` is set correctly, it is just not being used to generate the string. 

The following code produces a `Parameter` object that produces the incorrect string:
```
param_name = "A0"
param_value = "100"
parameter = bionetgen.modelapi.structs.Parameter(name = param_name, value = param_value)
print(parameter.gen_string())
print(p.value)
```

Output:
```
A0 None
100
```

Oddly enough, if you give the constructor both a `value` AND an `expr` that consists of something that can be cast to a `float`, it correctly chooses the `value` for the string:
```
param_name = "A0"
param_value = "100"
dummy_expr = "1276328.6487"
parameter = bionetgen.modelapi.structs.Parameter(name = param_name, value = param_value, expr = dummy_expr)
print(parameter.gen_string())
print(parameter.value)
print(parameter.expr)
```

Output:
```
A0 100
100
1276328.6487
```

**Comment by jrfaeder** [comment]
This was fixed by removing the expr attribute of the Parameter structure in commit 2f9785b1d16b8ab34cb66286e315c1fb23ed2950. This required small updates in xmlparsers.py. If expr attribute is defined in xml it overrides the value attribute. This was happening implicitly anyway.
