### ISSUE TITLE
Messages from BNG2.pl should display immediately when running from terminal

### ISSUE THREAD

**Issue by jrfaeder** [RuleWorld/PyBioNetGen#7]
Currently, for a model that runs slowly, the output is only generated after the simulation is complete or maybe when the output buffer is full? It should get written immediately; otherwise it is very difficult to figure out what part of the execution process is slowing down and it forces the user to resort to running BNG2.pl directly.

**Comment by ASinanSaglam** [comment]
[This commit](https://github.com/RuleWorld/PyBioNetGen/commit/9061a3cb976865595397108fc7b21217d079ecf8) should address this issue. Will close the issue if the release works well.

**Comment by ASinanSaglam** [comment]
I'll close this since the release is looking fine, we can re-open it if issues arise.

**Comment by jrfaeder** [comment]
👍
