### ISSUE TITLE
Reading invalid BNGL files should fail with a more informative error message

### ISSUE THREAD

**Issue by jonrkarr** [RuleWorld/PyBioNetGen#8]
Reading an invalid BNGL file
```python
import bionetgen
bionetgen.bngmodel('tests/fixtures/bngl/invalid.bngl')
```

fails with the error message 
```
...
FileNotFoundError: [Errno 2] No such file or directory
```

Also, if uncaught this causes a Python shell to exit.

It would be helpful for the exception or another data structure to capture informative information about the error.

**Comment by ASinanSaglam** [comment]
I will work on adding a full new set of exceptions to the library once I'm done with action reading.

**Comment by ASinanSaglam** [comment]
I started adding new exceptions, new version should have more informative error messages and expand them as I notice any areas they are lacking in. I'll close this and #41 for now, please feel free to re-open them or open new ones as you notice any lacking areas.
